package:
  name: pio
  version: 1.7.2

source:
  ftn: pio1_7_2.tar.gz
  url: https://github.com/NCAR/ParallelIO/archive/pio1_7_2.tar.gz
  md5: baac419a92c676df95ddcdde997487c2

build:
  number: 1

requirements:
  build:
    - netcdf-base
    - netcdf-fortran
    - parallel-netcdf
  run:
    - netcdf-base
    - netcdf-fortran
    - parallel-netcdf

test:

about:
  home: https://github.com/NCAR/ParallelIO
