package:
  name: netcdf-fortran
  version: 4.4.2

source:
  fn: netcdf-fortran-4.4.2.tar.gz
  url: http://www.gfd-dennou.org/library/netcdf/unidata-mirror/netcdf-fortran-4.4.2.tar.gz
  sha256: ad6249b6062df6f62f81d1cb2a072e3a4c595f27f11fe0c5a79726d1dad3143b

build:
  number: 1

requirements:
  build:
     - netcdf-base
  run:
     - netcdf-base

test:

about:
  home: http://www.unidata.ucar.edu/software/netcdf
